name: award_maker
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_snack_bar: ^0.4.0
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  rxdart: ^0.28.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  flutter_bloc: ^9.1.1
  logger: ^2.6.1
  flutter_screenutil: ^5.9.3
  google_fonts:
  get_it: ^8.2.0
  uuid: ^4.5.1

  # Use compatible versions for these two to avoid win32 conflict:
  device_info_plus:
  package_info_plus:

  firebase_messaging: ^16.0.0
  cached_network_image:
  pin_code_fields: ^8.0.1

  share_plus:

  google_sign_in: ^6.1.5
  flutter_local_notifications:
  webview_flutter: ^4.13.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"
  adaptive_icon_foreground: "assets/images/playstore.png"
  adaptive_icon_background: "#FFFFFF"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
